### ISSUE TITLE
About the SN75518N Driver

### ISSUE THREAD

**Issue by Dancopy** [MikeDombo/HV518_Arduino#1]
1) Can the SN75518N VFD Driver also be used with this library or does the SN75518N need no library (Arduino)?
2) How should it be declared / defined in the Arduino code to use the SN75518N?
Thank you

**Comment by Dancopy** [comment]
Greetings Michael! I would stay here again, asking for your help!
I have this display here: https://www.clitishop.top/samsung-temp-cook-time-svm06me08-vacuum-fluroescent-display-tube-part-m64-p-7943.htm and, as I mentioned, I would like to use it with obsolete SN75518 to make a clock, but I do not know what is the sequence to connect the SN75518 in the VFD Display and how to set the pins in the Arduino sketch or enjoy your library; The sequence of pins, from right to left is: 1-2, GND of Filament; 3-16, are anode segments; pin 17 not connected; 18-23 are Grids; 24-25, + 3V Filament. If you could kindly help me, I would be very grateful!

**Comment by MikeDombo** [comment]
Connect the anodes so that they are in the order as listed on http://www.uize.com/examples/seven-segment-display.html, using the G to A order and the decimal point as H. I can't help you anymore about how to connect the grid.

**Comment by Dancopy** [comment]
Hi Michael! Could you please fit my display (attached picture) to your sketch, considering that your two sketches (VFD.ino and VFD_ESP.ino) are for clock? It's just that I'm not familiar with these displays! Thank you very much
![display vfd esquematico](https://user-images.githubusercontent.com/37884487/48035475-49b20380-e14b-11e8-91f1-430b1848cde3.png)

**Comment by MikeDombo** [comment]
I unfortunately cannot help you and from looking at the picture, I do not think that this library can drive your display. It is made for a simple 7 segment display and not to be multiplexed like in your photo. You'll have to figure it out yourself.

**Comment by Dancopy** [comment]
Ok friend, thank you!
