### ISSUE TITLE
Total Shift Lines & left align display - Use

### ISSUE THREAD

**Issue by Dancopy** [MikeDombo/HV518_Arduino#2]
What does this two lines mean: 'Total Shift Lines' and 'left align display' because I have a vfd display with 5 digits, the colon being in digit 3 and, who knows I can adapt your library to my display!
Thank you

**Comment by MikeDombo** [comment]
Total shift lines is the total number of connections from the shift register. If I directly drive 1 7 segment display, that is 7 lines (or 8 with a period). 

Left align display is true if you want the text to be displayed all the way to the left. Use that mode for text. Set it to false for displaying numbers if you want the numbers to be right aligned. 
____10 would be right aligned and 10____ is left aligned.

**Comment by Dancopy** [comment]
Arduino: 1.8.5 (Windows 10), Placa:"Arduino/Genuino Uno"

D:\Arduino\Display Vacuum Fluorescent Driver\HV518_Arduino-master\HV518_Arduino-master\example\VFD\VFD.ino: In function 'void loop()':

VFD:86: error: 'class HV518' has no member named 'specialChars'

       disp.setDigit(6, disp.specialChars.colonDot);
                             ^
VFD:89: error: 'class HV518' has no member named 'specialChars'

       disp.setDigit(6, disp.specialChars.colonLine);
                             ^
exit status 1
'class HV518' has no member named 'specialChars'
