### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dancopy** [MikeDombo/HV518_Arduino#3]
Arduino: 1.8.5 (Windows 10), Placa:"Arduino/Genuino Uno"

D:\Arduino\Display Vacuum Fluorescent Driver\HV518_Arduino-master\HV518_Arduino-master\example\VFD\VFD.ino: In function 'void loop()':

VFD:86: error: 'class HV518' has no member named 'specialChars'

   disp.setDigit(6, disp.specialChars.colonDot);
                         ^
VFD:89: error: 'class HV518' has no member named 'specialChars'

   disp.setDigit(6, disp.specialChars.colonLine);
                         ^
exit status 1
'class HV518' has no member named 'specialChars'

**Comment by MikeDombo** [comment]
remove the `disp.` I just updated the example code.
