### ISSUE TITLE
Correlation of HV518 pins

### ISSUE THREAD

**Issue by Dancopy** [MikeDombo/HV518_Arduino#5]
Greetings Michael
First of all, congratulations on your HV518 Driver Library with Sample Clock for Arduino and ESP8266.
I do not understand how to correlate the 32 pins of the HV518 with the VFD display, because an Array of characters is not specified in the code. I mean the Grids and Anodes pins.
Taking advantage of the opportunity, is the HV518 similar to the SN75518N? Thanks

**Comment by MikeDombo** [comment]
The pins are expected to be ordered by the 7 segment display's segment order: https://components101.com/asset/sites/default/files/component_pin/7-segment-display-pin-diagr_0.png. A->G + dot.

This library is specifically for 7 segment displays, but the core logic could be reused for other types of displays or pin outs.

**Comment by Dancopy** [comment]
Thanks for the reply Michael
You said that your library is specifically for 7-segment displays, but the logic can be reused for other types of displays or pinouts. So, I have 7-segment displays but I also have 13-segment displays, but in this case, I would be using, from the 13, only 7 segments, from Grid 1 to Grid 6 and the colon (D2 and D1); so how should it be done, because I see that in the library, in the file HV518.h, in the line const static byte digits [] PROGMEM = {shows only the 1 byte binary (0b01111110, // 0). For 13 segments, shouldn't it be 2 2-byte binary arrays, leaving 3 bits left?
I would be using the display as in the attached image;
Once again, thank you very much
![Tabela de Grades e Anodos do Display Samsung HNV-07SS45T](https://user-images.githubusercontent.com/37884487/113636803-9a462780-9649-11eb-8b3d-b3225706e95e.jpg)

**Comment by MikeDombo** [comment]
So instead of byte you should be able to use short type which I believe is 2 bytes, or you can just make it an array of arrays as you suggest.

**Comment by Dancopy** [comment]
1) How would you do here 0b00001100, // 1 for 13 segments, for example?
2) And do you think the colon in the third and fifth digits will work?

**Comment by MikeDombo** [comment]
You will need to figure all of that out on your own. You aren't using the library as intended so I really cannot provide you any help.
